db_path: ./Databases/
db_name: ActivitiesDB
host: 0.0.0.0
port: 3003

activities:
  Personal:
    id: 1
    values:
      Sleep:
        id: 1
        external: no
      Eat:
        id: 2
        external: no
      Leisure:
        id: 3
        external: no
      Sports:
        id: 4
        external: no
      Other:
        id: 5
        external: no

  Academic:
    id: 2
    values:
      Attend classes:
        id: 1
        external: yes
        db: coursesDB
      Study:
        id: 2
        external: no

  Administrative:
    id: 3
    values:
      Presential service:
        id: 1
        external: yes
        db: presentialServicesDB
